type DpsPoint={damageEvent:number;dps:number};
type DamageItem={name:string;value:number};
type SimulationSummary={samples:number[];minimum:number;median:number;mean:number;maximum:number};

const WIDTH=1800,HEIGHT=1060,BACKGROUND="#090e17",PANEL="#101824",LINE="#263549",BLUE="#82d1ff",MUTED="#a4b4c9",TEXT="#edf4ff";

function canvas(){const element=document.createElement("canvas");element.width=WIDTH;element.height=HEIGHT;return element}
function context(element:HTMLCanvasElement){const value=element.getContext("2d");if(!value)throw new Error("canvas unavailable");value.textBaseline="middle";return value}
function font(ctx:CanvasRenderingContext2D,size:number,weight=400){ctx.font=`${weight} ${size}px "Noto Sans JP", Arial, sans-serif`}
function panel(ctx:CanvasRenderingContext2D,x:number,y:number,width:number,height:number){ctx.fillStyle=PANEL;ctx.strokeStyle=LINE;ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(x,y,width,height,18);ctx.fill();ctx.stroke()}
function label(ctx:CanvasRenderingContext2D,value:string,x:number,y:number){font(ctx,18,700);ctx.fillStyle=BLUE;ctx.fillText(value.toUpperCase(),x,y)}
function safeName(value:string){return value.replace(/[\\/:*?"<>|]/g,"-").trim()||"rotation"}
function save(element:HTMLCanvasElement,fileName:string){element.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=fileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),0)},"image/png")}
function header(ctx:CanvasRenderingContext2D,job:string,sheetName:string,title:string){label(ctx,"XIV ROTATION LAB",44,38);font(ctx,32,700);ctx.fillStyle=TEXT;ctx.fillText(title,44,78);font(ctx,18,400);ctx.fillStyle=MUTED;const contextText=`${job} · ${sheetName}`;ctx.fillText(contextText,WIDTH-44-ctx.measureText(contextText).width,78)}
function grid(ctx:CanvasRenderingContext2D,x:number,y:number,width:number,height:number){ctx.strokeStyle=LINE;ctx.lineWidth=2;for(let index=1;index<5;index++){const lineY=y+height*index/5;ctx.beginPath();ctx.moveTo(x,lineY);ctx.lineTo(x+width,lineY);ctx.stroke()}}
function drawTrend(ctx:CanvasRenderingContext2D,rows:DpsPoint[],x:number,y:number,width:number,height:number){grid(ctx,x,y,width,height);const points=rows.filter(row=>row.damageEvent>0&&Number.isFinite(row.dps));if(!points.length)return;const maxTime=Math.max(...points.map(row=>row.damageEvent),1),maxDps=Math.max(...points.map(row=>row.dps),1),coords=points.map(row=>[x+width*row.damageEvent/maxTime,y+height-height*row.dps/maxDps] as const),gradient=ctx.createLinearGradient(0,y,0,y+height);gradient.addColorStop(0,"rgba(88,191,255,.32)");gradient.addColorStop(1,"rgba(88,191,255,0)");ctx.beginPath();ctx.moveTo(coords[0][0],y+height);coords.forEach(([pointX,pointY])=>ctx.lineTo(pointX,pointY));ctx.lineTo(coords.at(-1)![0],y+height);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();coords.forEach(([pointX,pointY],index)=>index?ctx.lineTo(pointX,pointY):ctx.moveTo(pointX,pointY));ctx.strokeStyle=BLUE;ctx.lineWidth=4;ctx.stroke()}
function drawDistribution(ctx:CanvasRenderingContext2D,values:number[],x:number,y:number,width:number,height:number){grid(ctx,x,y,width,height);if(!values.length)return;const minimum=Math.min(...values),maximum=Math.max(...values),span=Math.max(maximum-minimum,1),binCount=Math.min(40,Math.max(12,Math.round(Math.sqrt(values.length)))),bins=new Array(binCount).fill(0);values.forEach(value=>{const index=Math.min(binCount-1,Math.floor((value-minimum)/span*binCount));bins[index]++});const tallest=Math.max(...bins,1),barWidth=width/binCount;bins.forEach((count,index)=>{const barHeight=height*count/tallest;ctx.fillStyle="rgba(88,191,255,.30)";ctx.fillRect(x+index*barWidth+2,y+height-barHeight,Math.max(2,barWidth-4),barHeight)});const mean=values.reduce((sum,value)=>sum+value,0)/values.length,variance=values.reduce((sum,value)=>sum+(value-mean)**2,0)/values.length,deviation=Math.max(Math.sqrt(variance),span/1000),peak=1/(deviation*Math.sqrt(2*Math.PI));ctx.beginPath();for(let pixel=0;pixel<=width;pixel++){const value=minimum+span*pixel/width,density=Math.exp(-.5*((value-mean)/deviation)**2)/(deviation*Math.sqrt(2*Math.PI)),pointX=x+pixel,pointY=y+height-height*.88*density/peak;if(pixel)ctx.lineTo(pointX,pointY);else ctx.moveTo(pointX,pointY)}ctx.strokeStyle=BLUE;ctx.lineWidth=4;ctx.stroke();font(ctx,16,400);ctx.fillStyle=MUTED;ctx.fillText(Math.round(minimum).toLocaleString(),x,y+height+24);ctx.textAlign="right";ctx.fillText(Math.round(maximum).toLocaleString(),x+width,y+height+24);ctx.textAlign="left"}

export function exportAnalysisImage(data:{job:string;sheetName:string;locale:"ja"|"en";dps:number;simulatedDps:number;iterations:number;rows:DpsPoint[];breakdown:DamageItem[];simulation:SimulationSummary}){
  const element=canvas(),ctx=context(element),ja=data.locale==="ja";
  ctx.fillStyle=BACKGROUND;ctx.fillRect(0,0,WIDTH,HEIGHT);header(ctx,data.job,data.sheetName,ja?"DPS分析":"DPS analysis");
  panel(ctx,40,110,1720,380);ctx.strokeStyle=LINE;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(390,110);ctx.lineTo(390,490);ctx.moveTo(1250,110);ctx.lineTo(1250,490);ctx.stroke();
  label(ctx,"DPS",72,150);font(ctx,72,700);ctx.fillStyle=TEXT;ctx.fillText(Math.round(data.dps).toLocaleString(),72,226);font(ctx,18,400);ctx.fillStyle=MUTED;ctx.fillText(`${ja?"シミュDPS":"Sim DPS"} ${Math.round(data.simulatedDps).toLocaleString()}`,72,290);ctx.fillText(`${data.iterations.toLocaleString()} ${ja?"試行":"runs"}`,72,324);
  label(ctx,ja?"DPS推移":"DPS TREND",424,150);drawTrend(ctx,data.rows,424,190,792,252);
  label(ctx,ja?"アクション別ダメージ":"DAMAGE BY ACTION",1284,150);const total=data.breakdown.reduce((sum,item)=>sum+item.value,0),top=data.breakdown.slice(0,6),maximumAction=Math.max(...top.map(item=>item.value),1);top.forEach((item,index)=>{const rowY=198+index*42;font(ctx,16,600);ctx.fillStyle=TEXT;const name=item.name.length>17?`${item.name.slice(0,16)}…`:item.name;ctx.fillText(name,1284,rowY);font(ctx,15,700);ctx.fillStyle=BLUE;ctx.textAlign="right";ctx.fillText(`${total?Math.round(item.value/total*100):0}%`,1724,rowY);ctx.textAlign="left";ctx.fillStyle="#1d2a31";ctx.fillRect(1284,rowY+15,440,7);ctx.fillStyle=BLUE;ctx.fillRect(1284,rowY+15,440*item.value/maximumAction,7)});
  panel(ctx,40,520,1120,500);label(ctx,ja?"正規分布":"DISTRIBUTION",72,558);drawDistribution(ctx,data.simulation.samples.filter(Number.isFinite),72,600,1056,350);
  panel(ctx,1180,520,220,500);label(ctx,"DPS",1208,558);font(ctx,46,700);ctx.fillStyle=BLUE;ctx.textAlign="center";ctx.fillText(Math.round(data.dps).toLocaleString(),1290,770);ctx.textAlign="left";
  const stats=[[ja?"平均値":"Mean",data.simulation.mean],[ja?"最大値":"Maximum",data.simulation.maximum],[ja?"中央値":"Median",data.simulation.median],[ja?"最小値":"Minimum",data.simulation.minimum]] as const;stats.forEach(([name,value],index)=>{const column=index%2,row=Math.floor(index/2),x=1420+column*176,y=520+row*258;panel(ctx,x,y,164,242);font(ctx,15,600);ctx.fillStyle=MUTED;ctx.fillText(name,x+16,y+50);font(ctx,27,700);ctx.fillStyle=BLUE;ctx.fillText(Math.round(value).toLocaleString(),x+16,y+132)});
  save(element,`${safeName(data.job)}-${safeName(data.sheetName)}-analysis.png`);
}
