"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Lane = "gcd" | "ability";
type Modifier = "none" | "delay" | "downtime" | "pre";
type ActionKind = Lane | "limitbreak";
type ActionFilter = "damage" | "support" | "gcd" | "ability" | "custom";
type Panel = "timeline" | "stats";
type Locale = "ja" | "en";
type ImportKind = "sheet" | "timeline" | "fflogs";
type ImportTarget = "both" | "actions" | "boss";
type CatalogAction = { id:number; name:string; lane:ActionKind; level:number|null; recast:number; cast:number; potency:number; iconPath:string; hasDamage:boolean; isReplacement:boolean; isAssignable:boolean };
type TimelineRow = { id:string; time:number; actionId:number|null; name:string; lane:Lane; potency:number; cast:number; recast:number; boss:string; iconPath:string; modifier:Modifier; modifierValue:number };
type Sheet = { id:string; name:string; job:string; rows:TimelineRow[] };
type Stats = { level:number; weapon:number; autoAttack:number; aaInterval:number; main:number; crit:number; dh:number; det:number; speed:number; tenacity:number; gcd:number };
type ComputedRow = TimelineRow & { prepare:number; damageEvent:number; nextGcd:number; nextOgcd:number; dps:number; sumPotency:number; aaCount:number; totalDamage:number; rowDamage:number; aaDamage:number };

const JOBS = ["PLD","WAR","DRK","GNB","WHM","SCH","AST","SGE","MNK","DRG","NIN","SAM","RPR","VPR","BRD","MCH","DNC","BLM","SMN","RDM","PCT"];
const JOB_NAMES:Record<string,string>={PLD:"ナイト",WAR:"戦士",DRK:"暗黒騎士",GNB:"ガンブレイカー",WHM:"白魔道士",SCH:"学者",AST:"占星術師",SGE:"賢者",MNK:"モンク",DRG:"竜騎士",NIN:"忍者",SAM:"侍",RPR:"リーパー",VPR:"ヴァイパー",BRD:"吟遊詩人",MCH:"機工士",DNC:"踊り子",BLM:"黒魔道士",SMN:"召喚士",RDM:"赤魔道士",PCT:"ピクトマンサー"};
const JOB_NAMES_EN:Record<string,string>={PLD:"Paladin",WAR:"Warrior",DRK:"Dark Knight",GNB:"Gunbreaker",WHM:"White Mage",SCH:"Scholar",AST:"Astrologian",SGE:"Sage",MNK:"Monk",DRG:"Dragoon",NIN:"Ninja",SAM:"Samurai",RPR:"Reaper",VPR:"Viper",BRD:"Bard",MCH:"Machinist",DNC:"Dancer",BLM:"Black Mage",SMN:"Summoner",RDM:"Red Mage",PCT:"Pictomancer"};
const TEXT={ja:{timeline:"タイムライン",stats:"ステータス",workspace:"ジョブ作業スペース",rotation:"ローテーション",import:"インポート",export:"エクスポート",expected:"予測DPS",dpsTrend:"DPS推移",breakdown:"アクション別ダメージ",gcd:"GCD",ogcd:"oGCD",aa:"AA",autoAttack:"オートアタック",actions:"アクション",search:"アクションを検索",damage:"ダメージあり",support:"ダメージなし",ability:"アビリティ",custom:"カスタム",nextAction:"次のアクション",none:"修飾子なし",seconds:"秒",undo:"1つ戻す",clear:"すべて消す",bossTimeline:"ボスタイムライン",time:"番号 / 時刻",potency:"威力",prepare:"バフ参照",sumPotency:"累計威力",boss:"ボス",empty:"タイムラインは空です",emptyHelp:"左のアクションリストから使用順に選択してください。",snapshot:"バフ参照は、詠唱アクションでは詠唱完了時、無詠唱アクションでは実行時点です。",characterInput:"キャラクター入力",saved:"ジョブ別にブラウザ保存",dataReady:"アクションデータ準備完了",expectedNote:"期待値・AA込み",loading:"読み込み中…",loadFailed:"アクションデータを読み込めませんでした",retry:"再読み込み",noActions:"該当するアクションはありません",deleteTitle:"シートを削除",deleteBody:"この操作は元に戻せません。",cancel:"キャンセル",delete:"削除する",importTitle:"タイムラインを読み込む",sheetFile:"シートJSON",timelineData:"CSV・貼り付け",logs:"イベントログ",file:"ファイルを選択",paste:"クリップボードから貼り付け",data:"データ",target:"読み込み先",both:"アクション＋ボス",actionsOnly:"アクションのみ",bossOnly:"ボスのみ",runImport:"読み込む",close:"閉じる",lang:"言語"},en:{timeline:"Timeline",stats:"Stats",workspace:"Job workspace",rotation:"rotation",import:"Import",export:"Export",expected:"Expected DPS",dpsTrend:"DPS trend",breakdown:"Damage by action",gcd:"GCD",ogcd:"oGCD",aa:"AA",autoAttack:"Auto-attack",actions:"Actions",search:"Search actions",damage:"Damage",support:"Utility",ability:"Abilities",custom:"Custom",nextAction:"Next action",none:"No modifier",seconds:"sec",undo:"Undo",clear:"Clear",bossTimeline:"Boss timeline",time:"# / Time",potency:"Potency",prepare:"Snapshot",sumPotency:"Sum potency",boss:"Boss",empty:"The timeline is empty",emptyHelp:"Choose actions from the palette in usage order.",snapshot:"Buffs are snapshotted on cast completion, or immediately for instant actions.",characterInput:"Character input",saved:"Saved in this browser by job",dataReady:"Action data ready",expectedNote:"Expected value · Includes AA",loading:"Loading…",loadFailed:"Could not load action data",retry:"Retry",noActions:"No matching actions",deleteTitle:"Delete sheet",deleteBody:"This action cannot be undone.",cancel:"Cancel",delete:"Delete",importTitle:"Import timeline",sheetFile:"Sheet JSON",timelineData:"CSV / Paste",logs:"Event log",file:"Choose file",paste:"Paste from clipboard",data:"Data",target:"Import target",both:"Actions + boss",actionsOnly:"Actions only",bossOnly:"Boss only",runImport:"Import",close:"Close",lang:"Language"}} as const;
const AA_INTERVALS:Record<string,number>={PLD:2.24,WAR:3.36,DRK:2.96,GNB:2.8,WHM:3.44,SCH:3.12,AST:3.2,SGE:2.8,MNK:2.56,DRG:2.8,NIN:2.56,SAM:2.64,RPR:3.2,VPR:2.64,BRD:3.04,MCH:2.64,DNC:3.12,BLM:3.28,SMN:3.12,RDM:3.44,PCT:2.96};
const LEVEL_MODS:Record<number,{main:number;sub:number;div:number;attack:number;tankAttack:number}>={70:{main:292,sub:364,div:900,attack:125,tankAttack:100},80:{main:340,sub:380,div:1300,attack:165,tankAttack:132},90:{main:390,sub:400,div:1900,attack:195,tankAttack:156},100:{main:440,sub:420,div:2780,attack:237,tankAttack:190}};
const JOB_MOD:Record<string,number>={PLD:100,WAR:105,DRK:105,GNB:100,WHM:115,SCH:115,AST:115,SGE:115,MNK:110,DRG:115,NIN:110,SAM:112,RPR:115,VPR:110,BRD:115,MCH:115,DNC:115,BLM:115,SMN:115,RDM:115,PCT:115};
const TRAIT:Record<string,number>={PLD:100,WAR:100,DRK:100,GNB:100,WHM:130,SCH:130,AST:130,SGE:130,MNK:100,DRG:100,NIN:100,SAM:100,RPR:100,VPR:100,BRD:120,MCH:120,DNC:120,BLM:130,SMN:130,RDM:130,PCT:130};
const TANKS=new Set(["PLD","WAR","DRK","GNB"]);
const STATS:Stats={level:100,weapon:152,autoAttack:110,aaInterval:2.24,main:5857,crit:3242,dh:1230,det:2883,speed:420,tenacity:420,gcd:2.5};
const STAT_LABELS:Record<keyof Stats,string>={level:"レベル",weapon:"武器基本性能",autoAttack:"AA性能",aaInterval:"AA間隔（秒）",main:"メインステータス",crit:"クリティカル",dh:"ダイレクトヒット",det:"意思力",speed:"スキル・スペルスピード",tenacity:"不屈",gcd:"基準GCD"};
const STAT_LABELS_EN:Record<keyof Stats,string>={level:"Level",weapon:"Weapon damage",autoAttack:"Auto-attack potency",aaInterval:"Auto-attack delay (sec)",main:"Main attribute",crit:"Critical Hit",dh:"Direct Hit",det:"Determination",speed:"Skill / Spell Speed",tenacity:"Tenacity",gcd:"Base GCD"};
const newSheet=(job:string,index=1):Sheet=>({id:crypto.randomUUID(),name:index===1?"本番回し":`比較案 ${index}`,job,rows:[]});
const iconUrl=(path:string)=>path?`https://v2.xivapi.com/api/asset?path=${encodeURIComponent(path)}&format=png`:"";
const timeText=(n:number)=>{const sign=n<0?"-":"";const v=Math.abs(n);return `${sign}${String(Math.floor(v/60)).padStart(2,"0")}:${(v%60).toFixed(1).padStart(4,"0")}`};
const decimal=(n:number)=>Number.isFinite(n)?n.toFixed(3).replace(/0+$/,"").replace(/\.$/,""):"0";
const savedNumber=(value:unknown,fallback:number)=>Number.isFinite(Number(value))?Number(value):fallback;
const normalizeStats=(stored:Partial<Stats>|undefined,fallback:Stats,legacy:{autoAttack?:unknown;aaInterval?:unknown}={}):Stats=>({level:[70,80,90,100].includes(Number(stored?.level))?Number(stored?.level):fallback.level,weapon:savedNumber(stored?.weapon,fallback.weapon),autoAttack:savedNumber(stored?.autoAttack,savedNumber(legacy.autoAttack,fallback.autoAttack)),aaInterval:savedNumber(stored?.aaInterval,savedNumber(legacy.aaInterval,fallback.aaInterval)),main:savedNumber(stored?.main,fallback.main),crit:savedNumber(stored?.crit,fallback.crit),dh:savedNumber(stored?.dh,fallback.dh),det:savedNumber(stored?.det,fallback.det),speed:savedNumber(stored?.speed,fallback.speed),tenacity:savedNumber(stored?.tenacity,fallback.tenacity),gcd:savedNumber(stored?.gcd,fallback.gcd)});
function parseDelimited(text:string){const delimiter=(text.split(/\r?\n/,1)[0]?.match(/\t/g)?.length||0)>(text.split(/\r?\n/,1)[0]?.match(/,/g)?.length||0)?"\t":",";const table:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){row.push(cell.trim());cell=""}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))table.push(row);row=[];cell=""}else cell+=char}row.push(cell.trim());if(row.some(Boolean))table.push(row);if(table.length<2)return[];const headers=table[0].map(value=>value.trim());return table.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??""])))}
function importRecords(text:string):Record<string,unknown>[] {const trimmed=text.trim();if(!trimmed)return[];if(trimmed.startsWith("{")||trimmed.startsWith("[")){const parsed=JSON.parse(trimmed),records=Array.isArray(parsed)?parsed:parsed.events||parsed.data?.events||parsed.entries||parsed.rows;return Array.isArray(records)?records:[]}return parseDelimited(trimmed)}
function recordValue(record:Record<string,unknown>,...keys:string[]){for(const key of keys){const direct=record[key];if(direct!==undefined&&direct!==null&&String(direct)!=="")return direct;const found=Object.keys(record).find(candidate=>candidate.toLowerCase()===key.toLowerCase());if(found)return record[found]}return undefined}
function eventName(record:Record<string,unknown>){const ability=record.ability as {name?:unknown}|undefined;return String(recordValue(record,"actionName","ability.name","abilityName","action","name","boss")??ability?.name??"")}
const expectedCritDh=(base:number,s:Stats,mod:{sub:number;div:number})=>{const critDelta=Math.floor(200*(s.crit-mod.sub)/mod.div),critRate=Math.max(0,Math.min(1,(critDelta+50)/1000)),critPower=1400+critDelta,dhRate=Math.max(0,Math.min(1,Math.floor(550*(s.dh-mod.sub)/mod.div)/1000)),normal=base,crit=Math.floor(base*critPower/1000),dh=Math.floor(base*125/100),cdh=Math.floor(crit*125/100);return normal*(1-critRate)*(1-dhRate)+crit*critRate*(1-dhRate)+dh*(1-critRate)*dhRate+cdh*critRate*dhRate};
const damageFactors=(s:Stats,job:string)=>{const mod=LEVEL_MODS[s.level]||LEVEL_MODS[100],tank=TANKS.has(job),attackCoeff=tank?mod.tankAttack:mod.attack,fAtk=Math.floor(attackCoeff*(s.main-mod.main)/mod.main)+100,fDet=Math.floor(140*(s.det-mod.main)/mod.div+1000),fTnc=tank?Math.floor(112*(s.tenacity-mod.sub)/mod.div+1000):1000,fWd=Math.floor(mod.main*JOB_MOD[job]/1000)+s.weapon,fSpd=Math.floor(130*(s.speed-mod.sub)/mod.div+1000);return{mod,fAtk,fDet,fTnc,fWd,fSpd,trait:TRAIT[job]||100}};
const directDamage=(potency:number,s:Stats,job:string)=>{const f=damageFactors(s,job);let value=Math.floor(potency*f.fAtk*f.fDet/100/1000);value=Math.floor(value*f.fTnc/1000);value=Math.floor(value*f.fWd/100);value=Math.floor(value*f.trait/100);return expectedCritDh(value,s,f.mod)};
const autoDamage=(s:Stats,job:string)=>{const f=damageFactors(s,job),fAuto=Math.floor(f.fWd*(s.aaInterval/3));let value=Math.floor(s.autoAttack*f.fAtk*f.fDet/100/1000);value=Math.floor(value*f.fTnc/1000);value=Math.floor(value*f.fSpd/1000);value=Math.floor(value*fAuto/100);value=Math.floor(value*f.trait/100);return expectedCritDh(value,s,f.mod)};

function calculate(rows:TimelineRow[],stats:Stats,job:string):ComputedRow[]{
  let nextGcd=0,nextOgcd=0,actionPotency=0,actionDamage=0;
  return rows.map(row=>{
    const prepare=row.actionId===null?row.time:row.time+Math.max(0,row.cast||0),damageEvent=prepare;
    let rowDamage=0;
    if(row.modifier==="delay"||row.modifier==="downtime"){nextGcd=Math.max(nextGcd,row.time)+Math.max(0,row.modifierValue);nextOgcd=Math.max(nextOgcd,row.time)+Math.max(0,row.modifierValue)}
    else{if(row.lane==="gcd")nextGcd=Math.max(nextGcd,row.time)+(row.recast||stats.gcd);nextOgcd=Math.max(nextOgcd,row.time)+.7;actionPotency+=Math.max(0,row.potency);rowDamage=directDamage(Math.max(0,row.potency),stats,job);actionDamage+=rowDamage}
    const aaCount=damageEvent>=0&&stats.aaInterval>0?Math.floor(damageEvent/stats.aaInterval)+1:0,sumPotency=actionPotency+aaCount*Math.max(0,stats.autoAttack),aaDamage=aaCount*autoDamage(stats,job),totalDamage=actionDamage+aaDamage;
    return {...row,prepare,damageEvent,nextGcd,nextOgcd,dps:damageEvent>0?totalDamage/damageEvent:0,sumPotency,aaCount,totalDamage,rowDamage,aaDamage};
  });
}

export default function Home(){
  const [job,setJob]=useState("PLD"),[sheets,setSheets]=useState<Sheet[]>([]),[active,setActive]=useState("");
  const [stats,setStats]=useState(STATS),[catalogs,setCatalogs]=useState<Record<string,CatalogAction[]>>({}),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState("");
  const [panel,setPanel]=useState<Panel>("timeline"),[filter,setFilter]=useState<ActionFilter>("damage"),[query,setQuery]=useState("");
  const [modifier,setModifier]=useState<Modifier>("none"),[modifierValue,setModifierValue]=useState(""),[bossOn,setBossOn]=useState(true),[saved,setSaved]=useState(false),[favoriteRevision,setFavoriteRevision]=useState(0),[draggingFavorite,setDraggingFavorite]=useState("");
  const [locale,setLocale]=useState<Locale>("ja"),[deleteTarget,setDeleteTarget]=useState<Sheet|null>(null),[importOpen,setImportOpen]=useState(false),[importKind,setImportKind]=useState<ImportKind>("sheet"),[logImportEnabled,setLogImportEnabled]=useState(false),[importTarget,setImportTarget]=useState<ImportTarget>("both"),[importText,setImportText]=useState(""),[importStatus,setImportStatus]=useState("");
  const hydrated=useRef(false),importInput=useRef<HTMLInputElement>(null);

  useEffect(()=>{const raw=localStorage.getItem("xiv-rotation-lab-v4")||localStorage.getItem("xiv-rotation-lab-v3")||localStorage.getItem("xiv-rotation-lab-v2");if(raw)try{const v=JSON.parse(raw),savedJob=JOBS.includes(v.job)?v.job:"PLD";setSheets((v.sheets||[]).map((s:Sheet)=>({...s,rows:(s.rows||[]).map(r=>({...r,cast:r.cast||0,recast:r.recast||0}))})));setActive(v.active||"");setJob(savedJob);setLocale(v.locale==="en"?"en":"ja");setStats(normalizeStats(v.stats,STATS,{autoAttack:v.configs?.[savedJob]?.aaPotency,aaInterval:v.configs?.[savedJob]?.aaInterval??AA_INTERVALS[savedJob]}))}catch{}hydrated.current=true},[]);
  useEffect(()=>{if(!hydrated.current)return;if(!sheets.some(s=>s.job===job)){const s=newSheet(job);setSheets(v=>[...v,s]);setActive(s.id)}else if(!sheets.some(s=>s.id===active&&s.job===job)){setActive(sheets.find(s=>s.job===job)!.id)}},[job,sheets,active]);
  useEffect(()=>{if(!hydrated.current)return;const t=setTimeout(()=>{localStorage.setItem("xiv-rotation-lab-v4",JSON.stringify({sheets,active,job,stats,locale}));setSaved(true);setTimeout(()=>setSaved(false),700)},250);return()=>clearTimeout(t)},[sheets,active,job,stats,locale]);
  useEffect(()=>{const key=`${job}:${locale}`;if(Object.prototype.hasOwnProperty.call(catalogs,key))return;setLoading(true);setLoadError("");fetch(`/api/actions?job=${job}&level=100&language=${locale}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error("action data unavailable");return data}).then(data=>setCatalogs(v=>({...v,[key]:data.actions||[]}))).catch(()=>setLoadError(TEXT[locale].loadFailed)).finally(()=>setLoading(false))},[job,locale,catalogs]);
  useEffect(()=>{const openLogImport=(event:KeyboardEvent)=>{if(event.ctrlKey&&event.shiftKey&&event.key.toLowerCase()==="l"){event.preventDefault();setLogImportEnabled(true);setImportKind("fflogs");setImportStatus("");setImportOpen(true)}};window.addEventListener("keydown",openLogImport);return()=>window.removeEventListener("keydown",openLogImport)},[]);

  const t=TEXT[locale],jobNames=locale==="ja"?JOB_NAMES:JOB_NAMES_EN,statLabels=locale==="ja"?STAT_LABELS:STAT_LABELS_EN,jobSheets=sheets.filter(s=>s.job===job),sheet=jobSheets.find(s=>s.id===active)||jobSheets[0],catalog=catalogs[`${job}:${locale}`]||[];
  const rows=sheet?.rows||[],runtimeRows=rows.map(row=>{const source=row.actionId===null?undefined:catalog.find(action=>action.id===row.actionId);return source?{...row,potency:source.potency,cast:source.cast,recast:source.recast}:row}),computed=calculate(runtimeRows,stats,job),last=computed.at(-1),expected=last?.dps||0;
  const damageTotals=new Map<string,number>();for(const row of computed){if(row.actionId!==null&&row.rowDamage>0)damageTotals.set(row.name,(damageTotals.get(row.name)||0)+row.rowDamage)}if((last?.aaDamage||0)>0)damageTotals.set(t.autoAttack,last!.aaDamage);const damageByAction=[...damageTotals].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);
  const favoriteKey=`xiv-rotation-favorites:${job}`;
  const favoriteOrder=useMemo(()=>{if(typeof window==="undefined")return [] as string[];try{return JSON.parse(localStorage.getItem(favoriteKey)||"[]") as string[]}catch{return []}},[favoriteKey,favoriteRevision]),favorites=useMemo(()=>new Set(favoriteOrder),[favoriteOrder]);
  const shown=useMemo(()=>catalog.filter(a=>(a.level??1)<=stats.level&&a.name.includes(query)&&(filter==="damage"?a.hasDamage:filter==="support"?!a.hasDamage:filter==="gcd"?a.lane==="gcd":filter==="ability"?a.lane==="ability"||a.lane==="limitbreak":favorites.has(String(a.id)))).sort((a,b)=>filter==="custom"?favoriteOrder.indexOf(String(a.id))-favoriteOrder.indexOf(String(b.id)):(a.level??999)-(b.level??999)||a.id-b.id),[catalog,filter,query,stats.level,favorites,favoriteOrder]);
  const setRows=(next:TimelineRow[])=>setSheets(v=>v.map(s=>s.id===sheet?.id?{...s,rows:next}:s));
  const pick=(a:CatalogAction)=>{const lane:Lane=a.lane==="gcd"?"gcd":"ability",ready=lane==="gcd"?(last?.nextGcd||0):(last?.nextOgcd||0),base=Math.max(last?.time||0,ready),amount=Math.max(0,Number(modifierValue)||0),time=modifier==="pre"?base-amount:base;setRows([...rows,{id:crypto.randomUUID(),time,actionId:a.id,name:a.name,lane,potency:a.potency||0,cast:a.cast||0,recast:a.recast||0,boss:"",iconPath:a.iconPath,modifier,modifierValue:amount}]);setModifier("none");setModifierValue("")};
  const addPseudo=(kind:"delay"|"downtime")=>{const time=Math.max(last?.nextGcd||0,last?.nextOgcd||0,last?.time||0);setRows([...rows,{id:crypto.randomUUID(),time,actionId:null,name:kind==="delay"?"ディレイ":"ダウンタイム",lane:"ability",potency:0,cast:0,recast:0,boss:"",iconPath:"",modifier:kind,modifierValue:Math.max(.1,Number(modifierValue)||1)}]);setModifierValue("")};
  const addSheet=()=>{const s=newSheet(job,jobSheets.length+1);setSheets(v=>[...v,s]);setActive(s.id)};
  const deleteSheet=()=>{if(!deleteTarget)return;const remaining=jobSheets.filter(s=>s.id!==deleteTarget.id);setSheets(v=>v.filter(s=>s.id!==deleteTarget.id));if(active===deleteTarget.id)setActive(remaining[0]?.id||"");setDeleteTarget(null)};
  const exportSheet=()=>{if(!sheet)return;const payload={format:"xiv-rotation-lab-sheet",version:1,exportedAt:new Date().toISOString(),stats,sheet:{name:sheet.name,job:sheet.job,rows:sheet.rows}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${sheet.job}-${sheet.name.replace(/[\\/:*?\"<>|]/g,"-")}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
  const importSheetJson=(text:string)=>{const parsed=JSON.parse(text),source=parsed?.format==="xiv-rotation-lab-sheet"?parsed.sheet:parsed;if(!source||!JOBS.includes(source.job)||!Array.isArray(source.rows))throw new Error("invalid sheet");const modifiers:Modifier[]=["none","delay","downtime","pre"],sheetRows:TimelineRow[]=source.rows.map((r:Partial<TimelineRow>)=>({id:crypto.randomUUID(),time:Number(r.time)||0,actionId:r.actionId===null?null:Number.isFinite(Number(r.actionId))?Number(r.actionId):null,name:String(r.name||""),lane:r.lane==="gcd"?"gcd":"ability",potency:Number(r.potency)||0,cast:Number(r.cast)||0,recast:Number(r.recast)||0,boss:String(r.boss||""),iconPath:String(r.iconPath||""),modifier:modifiers.includes(r.modifier as Modifier)?r.modifier as Modifier:"none",modifierValue:Number(r.modifierValue)||0}));const imported:Sheet={id:crypto.randomUUID(),name:String(source.name||"Imported sheet"),job:source.job,rows:sheetRows};setSheets(v=>[...v,imported]);if(parsed?.stats)setStats(normalizeStats(parsed.stats,stats));setJob(imported.job);setActive(imported.id);return sheetRows.length};
  const importTimelineText=(text:string)=>{
    const records=importRecords(text);if(!records.length)throw new Error("no records");
    const rawTimes=records.map(record=>Number(recordValue(record,"time","timestamp","relativeTime","start"))).filter(Number.isFinite),minimum=rawTimes.length?Math.min(...rawTimes):0,epochMs=minimum>1e11,epochSeconds=!epochMs&&minimum>1e8;
    const actionRows:TimelineRow[]=[],bossEvents:{time:number;name:string}[]=[];
    for(const record of records){
      const rawTime=Number(recordValue(record,"time","timestamp","relativeTime","start")),time=Number.isFinite(rawTime)?Math.max(0,epochMs?(rawTime-minimum)/1000:epochSeconds?rawTime-minimum:rawTime):0,ability=record.ability as {gameID?:unknown;id?:unknown;name?:unknown}|undefined,idValue=recordValue(record,"actionId","abilityGameID","ability.id","id")??ability?.gameID??ability?.id,actionId=Number(idValue),name=eventName(record),explicitBoss=String(recordValue(record,"boss","bossAction","enemyAction")||""),laneValue=String(recordValue(record,"lane","kind","category")||"").toLowerCase(),match=(Number.isFinite(actionId)?catalog.find(action=>action.id===actionId):undefined)||catalog.find(action=>action.name===name),isAction=importTarget==="actions"||importTarget==="both"&&(Boolean(match)||laneValue==="gcd"||laneValue==="ability"||laneValue==="ogcd");
      if(importTarget!=="actions"&&explicitBoss)bossEvents.push({time,name:explicitBoss});
      if(importTarget!=="boss"&&isAction&&(match||name||Number.isFinite(actionId)))actionRows.push({id:crypto.randomUUID(),time,actionId:match?.id??(Number.isFinite(actionId)?actionId:null),name:match?.name||name||`Action ${actionId}`,lane:match?.lane==="gcd"||laneValue==="gcd"?"gcd":"ability",potency:match?.potency||0,cast:match?.cast||0,recast:match?.recast||0,boss:"",iconPath:match?.iconPath||"",modifier:"none",modifierValue:0});
      else if(importTarget!=="actions"&&!explicitBoss&&name)bossEvents.push({time,name});
    }
    actionRows.sort((a,b)=>a.time-b.time);const base=actionRows.length?actionRows:importTarget==="boss"?[...rows]:[],merged=[...base];
    for(const event of bossEvents){let nearest=-1,distance=Infinity;merged.forEach((row,index)=>{const delta=Math.abs(row.time-event.time);if(delta<distance){nearest=index;distance=delta}});if(nearest>=0&&distance<=.75&&!merged[nearest].boss)merged[nearest]={...merged[nearest],boss:event.name};else merged.push({id:crypto.randomUUID(),time:event.time,actionId:null,name:"",lane:"ability",potency:0,cast:0,recast:0,boss:event.name,iconPath:"",modifier:"none",modifierValue:0})}
    merged.sort((a,b)=>a.time-b.time);if(importTarget==="boss")setRows(merged);else{const imported:Sheet={id:crypto.randomUUID(),name:locale==="ja"?"ログ取込":"Log import",job,rows:merged};setSheets(v=>[...v,imported]);setActive(imported.id)}return{actions:actionRows.length,boss:bossEvents.length};
  };
  const runImport=()=>{try{if(importKind==="sheet"){const count=importSheetJson(importText);setImportStatus(locale==="ja"?`${count}行のシートを読み込みました。`:`Imported a ${count}-row sheet.`)}else{const result=importTimelineText(importText);setImportStatus(locale==="ja"?`アクション ${result.actions}件、ボス ${result.boss}件を読み込みました。`:`Imported ${result.actions} actions and ${result.boss} boss events.`)}setTimeout(()=>{setImportOpen(false);setImportText("");setImportStatus("")},700)}catch{setImportStatus(locale==="ja"?"形式を確認できませんでした。列名とデータを確認してください。":"Could not recognize the data format or columns.")}};
  const readImportFile=async(file?:File)=>{if(!file)return;setImportText(await file.text());if(importKind!=="fflogs")setImportKind(file.name.toLowerCase().endsWith(".json")?"sheet":"timeline");setImportStatus(`${file.name} (${Math.ceil(file.size/1024)} KB)`);if(importInput.current)importInput.current.value=""};
  const pasteClipboard=async()=>{try{setImportText(await navigator.clipboard.readText());setImportStatus(locale==="ja"?"クリップボードから貼り付けました。":"Pasted from clipboard.")}catch{setImportStatus(locale==="ja"?"テキスト欄へ直接貼り付けてください。":"Paste directly into the text area.")}};
  const updateRow=(id:string,patch:Partial<TimelineRow>)=>setRows(rows.map(r=>r.id===id?{...r,...patch}:r));
  const saveFavoriteOrder=(order:string[])=>{localStorage.setItem(favoriteKey,JSON.stringify(order));setFavoriteRevision(v=>v+1)};
  const toggleFavorite=(id:number)=>{const key=String(id);saveFavoriteOrder(favorites.has(key)?favoriteOrder.filter(x=>x!==key):[...favoriteOrder,key])};
  const reorderFavorite=(target:string)=>{if(!draggingFavorite||draggingFavorite===target)return;const next=favoriteOrder.filter(x=>x!==draggingFavorite),index=next.indexOf(target);next.splice(index<0?next.length:index,0,draggingFavorite);saveFavoriteOrder(next);setDraggingFavorite("")};
  const retryActions=()=>setCatalogs(v=>{const next={...v};delete next[`${job}:${locale}`];return next});

  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">X</span><div><strong>XIV ROTATION LAB</strong><small>DPS SIMULATOR</small></div></div><nav><Nav value="timeline" panel={panel} setPanel={setPanel}>{t.timeline}</Nav><Nav value="stats" panel={panel} setPanel={setPanel}>{t.stats}</Nav></nav><label className="language-control">{t.lang}<select value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="ja">日本語</option><option value="en">English</option></select></label></header>
    <section className="sheet-head"><div><p className="eyebrow">{t.workspace}</p><div className="job-title"><select value={job} onChange={e=>setJob(e.target.value)}>{JOBS.map(j=><option key={j} value={j}>{j} — {jobNames[j]}</option>)}</select><label className="level-select">LEVEL<select value={stats.level} onChange={e=>setStats({...stats,level:Number(e.target.value)})}>{[70,80,90,100].map(level=><option key={level} value={level}>Lv. {level}</option>)}</select></label><h1>{jobNames[job]} {t.rotation}</h1></div></div><div className="sheet-tools"><button onClick={()=>{setImportOpen(true);setImportStatus("")}}>{t.import}</button><button onClick={exportSheet} disabled={!sheet}>{t.export}</button><input ref={importInput} type="file" accept="application/json,.json,text/csv,.csv,text/plain,.txt" hidden onChange={e=>readImportFile(e.target.files?.[0])}/><div className="tabs">{jobSheets.map(s=><span key={s.id} className={`sheet-tab ${s.id===sheet?.id?"active":""}`}><button onClick={()=>setActive(s.id)}>{s.name}</button><button className="tab-delete" aria-label={`${s.name}を削除`} onClick={()=>setDeleteTarget(s)}>×</button></span>)}<button className="plus" aria-label="シートを追加" onClick={addSheet}>＋</button></div></div></section>
    <section className="analysis-strip"><article className="dps-summary"><span>{t.expected}</span><strong>{Math.round(expected).toLocaleString()}</strong><small>{t.expectedNote}</small></article><article className="chart-card"><span>{t.dpsTrend}</span><DpsChart rows={computed}/></article><article className="chart-card breakdown-card"><span>{t.breakdown}</span><DamageBreakdown items={damageByAction}/></article></section>
    {loadError&&<section className="api-error"><span>{loadError}</span><button onClick={retryActions}>{t.retry}</button></section>}

    {panel==="timeline"&&<section className="timeline-workbench">
      <ActionDock shown={shown} loading={loading} loadError={loadError} filter={filter} setFilter={setFilter} query={query} setQuery={setQuery} favorites={favorites} toggleFavorite={toggleFavorite} pick={pick} modifier={modifier} setModifier={setModifier} modifierValue={modifierValue} setModifierValue={setModifierValue} nextGcd={last?.nextGcd||0} nextOgcd={last?.nextOgcd||0} draggingFavorite={draggingFavorite} setDraggingFavorite={setDraggingFavorite} reorderFavorite={reorderFavorite} text={t}/>
      <div className="timeline-main"><div className="system-toolbar"><div className="modifier-controls"><input aria-label="modifier seconds" type="number" step=".1" placeholder="0" value={modifierValue} onChange={e=>setModifierValue(e.target.value)}/><span>{t.seconds}</span><button onClick={()=>addPseudo("delay")}>DELAY</button><button onClick={()=>addPseudo("downtime")}>DOWNTIME</button></div><div className="timeline-actions"><button onClick={()=>setRows(rows.slice(0,-1))} disabled={!rows.length}>{t.undo}</button><button onClick={()=>setRows([])} disabled={!rows.length}>{t.clear}</button></div><label><input type="checkbox" checked={bossOn} onChange={e=>setBossOn(e.target.checked)}/> {t.bossTimeline}</label></div>
        <div className="timeline-table-wrap"><table className="timeline-table"><thead><tr><th>{t.time}</th><th>GCD</th><th>oGCD</th><th>{t.potency}</th><th>{t.prepare}</th><th>NEXT GCD</th><th>NEXT oGCD</th><th>DPS</th><th>{t.sumPotency}</th><th>AA</th>{bossOn&&<th>{t.boss}</th>}</tr></thead><tbody>{computed.map((r,i)=><tr key={r.id}><td className="row-time"><b>{String(i+1).padStart(2,"0")}</b><span>{timeText(r.time)}</span>{r.modifier!=="none"&&<em>{r.modifier} {r.modifierValue}</em>}</td><td>{r.lane==="gcd"?<ActionCell row={r} onDelete={id=>setRows(rows.filter(x=>x.id!==id))}/>:null}</td><td>{r.lane==="ability"?<ActionCell row={r} onDelete={id=>setRows(rows.filter(x=>x.id!==id))}/>:null}</td><td className="potency-cell">{r.actionId===null?"—":r.potency||"—"}</td><td>{decimal(r.prepare)}</td><td>{decimal(r.nextGcd)}</td><td>{decimal(r.nextOgcd)}</td><td className="damage">{Math.round(r.dps).toLocaleString()}</td><td>{r.sumPotency.toLocaleString()}</td><td>{r.aaCount}</td>{bossOn&&<td className={`boss-cell ${r.boss?"has-value":""}`}><input aria-label={t.boss} value={r.boss} onChange={e=>updateRow(r.id,{boss:e.target.value})}/></td>}</tr>)}</tbody></table>{!computed.length&&<div className="empty-state"><b>{job} {t.empty}</b><span>{t.emptyHelp}</span></div>}</div>
        <p className="snapshot-note">{t.snapshot}</p></div>
    </section>}
    {panel==="stats"&&<section className="form-card"><div className="section-title"><div><p className="eyebrow">{t.characterInput}</p><h2>{job} {t.stats}</h2></div></div><div className="form-grid">{Object.entries(stats).filter(([k])=>k!=="level").map(([k,v])=><label key={k}>{statLabels[k as keyof Stats]}<input type="number" value={v} step={["gcd","aaInterval","autoAttack"].includes(k)?.01:1} onChange={e=>setStats({...stats,[k]:Number(e.target.value)})}/></label>)}</div></section>}
    <footer><span><b className="dot"/> {t.saved}{saved?" ✓":""}</span><span>{t.dataReady}</span></footer>
    {deleteTarget&&<div className="modal-backdrop" onMouseDown={()=>setDeleteTarget(null)}><section className="app-modal confirm-modal" role="dialog" aria-modal="true" aria-labelledby="delete-title" onMouseDown={e=>e.stopPropagation()}><div className="modal-icon">×</div><h2 id="delete-title">{t.deleteTitle}</h2><p>「{deleteTarget.name}」</p><small>{t.deleteBody}</small><div className="modal-actions"><button onClick={()=>setDeleteTarget(null)}>{t.cancel}</button><button className="danger" onClick={deleteSheet}>{t.delete}</button></div></section></div>}
    {importOpen&&<div className="modal-backdrop" onMouseDown={()=>setImportOpen(false)}><section className="app-modal import-modal" role="dialog" aria-modal="true" aria-labelledby="import-title" onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">IMPORT WORKFLOW</p><h2 id="import-title">{t.importTitle}</h2></div><button aria-label={t.close} onClick={()=>setImportOpen(false)}>×</button></header><div className="import-tabs">{([['sheet',t.sheetFile],['timeline',t.timelineData],...(logImportEnabled?[["fflogs",t.logs] as [ImportKind,string]]:[])] as [ImportKind,string][]).map(([value,label])=><button key={value} className={importKind===value?"active":""} onClick={()=>{setImportKind(value);setImportStatus("")}}>{label}</button>)}</div><div className="import-guide">{importKind==="sheet"?(locale==="ja"?"このツールから書き出したJSONを、新しいシートとして復元します。":"Restore an exported JSON file as a new sheet."):importKind==="timeline"?(locale==="ja"?"CSV/TSV列: time, actionId, actionName, lane, boss。アクションまたはボスだけでも読み込めます。":"CSV/TSV columns: time, actionId, actionName, lane, boss. Actions and boss events may be imported separately."):(locale==="ja"?"castイベントJSON/CSVを、timestamp、abilityGameID、ability.nameから正規化します。":"Normalizes cast-event JSON/CSV using timestamp, abilityGameID and ability.name.")}</div><div className="import-buttons"><button onClick={()=>importInput.current?.click()}>{t.file}</button><button onClick={pasteClipboard}>{t.paste}</button></div>{importKind!=="sheet"&&<label className="import-target">{t.target}<select value={importTarget} onChange={e=>setImportTarget(e.target.value as ImportTarget)}><option value="both">{t.both}</option><option value="actions">{t.actionsOnly}</option><option value="boss">{t.bossOnly}</option></select></label>}<label className="import-data">{t.data}<textarea value={importText} onChange={e=>setImportText(e.target.value)} placeholder={importKind==="sheet"?'{ "format": "xiv-rotation-lab-sheet", ... }':importKind==="fflogs"?'timestamp,type,abilityGameID,ability.name':'time,actionId,actionName,lane,boss'}/></label><p className={`import-status ${importStatus.includes("確認")||importStatus.includes("Could not")?"error":""}`} role="status">{importStatus}</p><div className="modal-actions"><button onClick={()=>setImportOpen(false)}>{t.cancel}</button><button className="primary" disabled={!importText.trim()} onClick={runImport}>{t.runImport}</button></div></section></div>}
  </main>
}

function Nav({value,panel,setPanel,children}:{value:Panel;panel:Panel;setPanel:(v:Panel)=>void;children:React.ReactNode}){return <button className={panel===value?"nav-active":""} onClick={()=>setPanel(value)}>{children}</button>}

function ActionDock({shown,loading,loadError,filter,setFilter,query,setQuery,favorites,toggleFavorite,pick,modifier,setModifier,modifierValue,setModifierValue,nextGcd,nextOgcd,draggingFavorite,setDraggingFavorite,reorderFavorite,text}:{shown:CatalogAction[];loading:boolean;loadError:string;filter:ActionFilter;setFilter:(v:ActionFilter)=>void;query:string;setQuery:(v:string)=>void;favorites:Set<string>;toggleFavorite:(id:number)=>void;pick:(a:CatalogAction)=>void;modifier:Modifier;setModifier:(v:Modifier)=>void;modifierValue:string;setModifierValue:(v:string)=>void;nextGcd:number;nextOgcd:number;draggingFavorite:string;setDraggingFavorite:(v:string)=>void;reorderFavorite:(v:string)=>void;text:Record<string,string>}){
  return <aside className="action-dock"><div className="dock-heading"><div><p className="eyebrow">ACTION PALETTE</p><h2>{text.actions}</h2></div><div className="ready-times"><span>NEXT GCD <b>{decimal(nextGcd)}</b></span><span>NEXT oGCD <b>{decimal(nextOgcd)}</b></span></div></div><input className="action-search" placeholder={text.search} value={query} onChange={e=>setQuery(e.target.value)}/><div className="filter-tabs">{([["damage",text.damage],["support",text.support],["gcd","GCD"],["ability",text.ability],["custom",text.custom]] as [ActionFilter,string][]).map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className="dock-modifier"><span>{text.nextAction}</span><select value={modifier} onChange={e=>setModifier(e.target.value as Modifier)}><option value="none">{text.none}</option><option value="pre">PRE</option></select>{modifier==="pre"&&<><input aria-label="PRE" type="number" min="0" step=".1" placeholder="0" value={modifierValue} onChange={e=>setModifierValue(e.target.value)}/><span>{text.seconds}</span></>}</div><div className="studio-action-list">{shown.map(a=>{const key=String(a.id);return <article key={`${a.id}:${a.name}`} draggable={filter==="custom"} className={draggingFavorite===key?"dragging":""} onDragStart={()=>setDraggingFavorite(key)} onDragEnd={()=>setDraggingFavorite("")} onDragOver={e=>{if(filter==="custom")e.preventDefault()}} onDrop={()=>reorderFavorite(key)}>{filter==="custom"&&<span className="drag-handle" title="drag">⠿</span>}<button className="action-choice" onClick={()=>pick(a)}><img src={iconUrl(a.iconPath)} alt=""/><span><b>{a.name}</b><small>{a.lane==="gcd"?"GCD":a.lane==="limitbreak"?"LIMIT BREAK":text.ability}{a.isReplacement?" · replace":""} · Lv.{a.level??"—"} · {text.potency} {a.potency||"—"}</small></span></button><button className={favorites.has(key)?"favorite active":"favorite"} aria-label="favorite" onClick={()=>toggleFavorite(a.id)}>{favorites.has(key)?"★":"☆"}</button></article>})}{!shown.length&&<p className="no-results">{loading?text.loading:loadError?text.loadFailed:text.noActions}</p>}</div></aside>
}

function ActionCell({row,onDelete}:{row:TimelineRow;onDelete:(id:string)=>void}){if(row.actionId===null&&!row.name)return null;return <span className={`action-cell ${row.modifier==="delay"||row.modifier==="downtime"?"pseudo":""}`}>{row.iconPath?<img src={iconUrl(row.iconPath)} alt=""/>:<i>{row.modifier==="delay"?"⏱":"⇥"}</i>}<span><b>{row.name}</b>{row.cast>0&&<small>CAST {row.cast.toFixed(1)}s</small>}</span><button aria-label="削除" onClick={()=>onDelete(row.id)}>×</button></span>}

function DpsChart({rows}:{rows:ComputedRow[]}){const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{const element=canvas.current;if(!element)return;const draw=()=>{const rect=element.getBoundingClientRect(),ratio=window.devicePixelRatio||1;element.width=Math.max(1,rect.width*ratio);element.height=Math.max(1,rect.height*ratio);const context=element.getContext("2d");if(!context)return;context.scale(ratio,ratio);const width=rect.width,height=rect.height,pad=8,points=rows.filter(row=>row.damageEvent>0);context.clearRect(0,0,width,height);context.strokeStyle="#29332b";context.lineWidth=1;for(let i=1;i<4;i++){const y=pad+(height-pad*2)*i/4;context.beginPath();context.moveTo(pad,y);context.lineTo(width-pad,y);context.stroke()}if(!points.length)return;const maxTime=Math.max(...points.map(row=>row.damageEvent),1),maxDps=Math.max(...points.map(row=>row.dps),1),coords=points.map(row=>[pad+(width-pad*2)*row.damageEvent/maxTime,height-pad-(height-pad*2)*row.dps/maxDps]);const gradient=context.createLinearGradient(0,0,0,height);gradient.addColorStop(0,"rgba(183,240,90,.28)");gradient.addColorStop(1,"rgba(183,240,90,0)");context.beginPath();context.moveTo(coords[0][0],height-pad);coords.forEach(([x,y])=>context.lineTo(x,y));context.lineTo(coords.at(-1)![0],height-pad);context.closePath();context.fillStyle=gradient;context.fill();context.beginPath();coords.forEach(([x,y],index)=>index?context.lineTo(x,y):context.moveTo(x,y));context.strokeStyle="#b7f05a";context.lineWidth=2;context.stroke()};draw();const observer=new ResizeObserver(draw);observer.observe(element);return()=>observer.disconnect()},[rows]);return <canvas className="dps-chart" ref={canvas} aria-label="DPS chart"/>}

function DamageBreakdown({items}:{items:{name:string;value:number}[]}){const colors=["#b7f05a","#78cfff","#ff9b54","#d59bff","#ffd166","#65d6ad","#ff718b","#8ea7ff","#e8e269","#75d0e8"],total=items.reduce((sum,item)=>sum+item.value,0);let offset=0;const segments=items.map((item,index)=>{const start=offset,end=offset+(total?item.value/total*100:0);offset=end;return `${colors[index%colors.length]} ${start}% ${end}%`}),style={background:total?`conic-gradient(${segments.join(",")})`:"#262c27"};return <div className="breakdown"><div className="donut" style={style}><span>{total?Math.round(total).toLocaleString():"—"}</span></div><div className="chart-legend">{items.map((item,index)=><div key={item.name}><i style={{background:colors[index%colors.length]}}/><span title={item.name}>{item.name}</span><b>{total?Math.round(item.value/total*100):0}%</b></div>)}</div></div>}
