"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Lane = "gcd" | "ability";
type Modifier = "none" | "delay" | "downtime" | "pre";
type ActionKind = Lane | "limitbreak";
type ActionFilter = "damage" | "support" | "gcd" | "ability" | "custom";
type Panel = "timeline" | "stats";
type CatalogAction = { id:number; name:string; lane:ActionKind; level:number|null; recast:number; cast:number; potency:number; iconPath:string; hasDamage:boolean; isReplacement:boolean; isAssignable:boolean };
type TimelineRow = { id:string; time:number; actionId:number|null; name:string; lane:Lane; potency:number; cast:number; recast:number; boss:string; iconPath:string; modifier:Modifier; modifierValue:number };
type Sheet = { id:string; name:string; job:string; rows:TimelineRow[] };
type Stats = { level:number; weapon:number; autoAttack:number; aaInterval:number; main:number; crit:number; dh:number; det:number; speed:number; tenacity:number; gcd:number };
type ComputedRow = TimelineRow & { prepare:number; damageEvent:number; nextGcd:number; nextOgcd:number; dps:number; sumPotency:number; aaCount:number; totalDamage:number };

const JOBS = ["PLD","WAR","DRK","GNB","WHM","SCH","AST","SGE","MNK","DRG","NIN","SAM","RPR","VPR","BRD","MCH","DNC","BLM","SMN","RDM","PCT"];
const JOB_NAMES:Record<string,string>={PLD:"ナイト",WAR:"戦士",DRK:"暗黒騎士",GNB:"ガンブレイカー",WHM:"白魔道士",SCH:"学者",AST:"占星術師",SGE:"賢者",MNK:"モンク",DRG:"竜騎士",NIN:"忍者",SAM:"侍",RPR:"リーパー",VPR:"ヴァイパー",BRD:"吟遊詩人",MCH:"機工士",DNC:"踊り子",BLM:"黒魔道士",SMN:"召喚士",RDM:"赤魔道士",PCT:"ピクトマンサー"};
const AA_INTERVALS:Record<string,number>={PLD:2.24,WAR:3.36,DRK:2.96,GNB:2.8,WHM:3.44,SCH:3.12,AST:3.2,SGE:2.8,MNK:2.56,DRG:2.8,NIN:2.56,SAM:2.64,RPR:3.2,VPR:2.64,BRD:3.04,MCH:2.64,DNC:3.12,BLM:3.28,SMN:3.12,RDM:3.44,PCT:2.96};
const LEVEL_MODS:Record<number,{main:number;sub:number;div:number;attack:number;tankAttack:number}>={70:{main:292,sub:364,div:900,attack:125,tankAttack:100},80:{main:340,sub:380,div:1300,attack:165,tankAttack:132},90:{main:390,sub:400,div:1900,attack:195,tankAttack:156},100:{main:440,sub:420,div:2780,attack:237,tankAttack:190}};
const JOB_MOD:Record<string,number>={PLD:100,WAR:105,DRK:105,GNB:100,WHM:115,SCH:115,AST:115,SGE:115,MNK:110,DRG:115,NIN:110,SAM:112,RPR:115,VPR:110,BRD:115,MCH:115,DNC:115,BLM:115,SMN:115,RDM:115,PCT:115};
const TRAIT:Record<string,number>={PLD:100,WAR:100,DRK:100,GNB:100,WHM:130,SCH:130,AST:130,SGE:130,MNK:100,DRG:100,NIN:100,SAM:100,RPR:100,VPR:100,BRD:120,MCH:120,DNC:120,BLM:130,SMN:130,RDM:130,PCT:130};
const TANKS=new Set(["PLD","WAR","DRK","GNB"]);
const STATS:Stats={level:100,weapon:152,autoAttack:110,aaInterval:2.24,main:5857,crit:3242,dh:1230,det:2883,speed:420,tenacity:420,gcd:2.5};
const STAT_LABELS:Record<keyof Stats,string>={level:"レベル",weapon:"武器基本性能",autoAttack:"AA性能",aaInterval:"AA間隔（秒）",main:"メインステータス",crit:"クリティカル",dh:"ダイレクトヒット",det:"意思力",speed:"スキル・スペルスピード",tenacity:"不屈",gcd:"基準GCD"};
const newSheet=(job:string,index=1):Sheet=>({id:crypto.randomUUID(),name:index===1?"本番回し":`比較案 ${index}`,job,rows:[]});
const iconUrl=(path:string)=>path?`https://v2.xivapi.com/api/asset?path=${encodeURIComponent(path)}&format=png`:"";
const timeText=(n:number)=>{const sign=n<0?"-":"";const v=Math.abs(n);return `${sign}${String(Math.floor(v/60)).padStart(2,"0")}:${(v%60).toFixed(1).padStart(4,"0")}`};
const decimal=(n:number)=>Number.isFinite(n)?n.toFixed(3).replace(/0+$/,"").replace(/\.$/,""):"0";
const savedNumber=(value:unknown,fallback:number)=>Number.isFinite(Number(value))?Number(value):fallback;
const normalizeStats=(stored:Partial<Stats>|undefined,fallback:Stats,legacy:{autoAttack?:unknown;aaInterval?:unknown}={}):Stats=>({level:[70,80,90,100].includes(Number(stored?.level))?Number(stored?.level):fallback.level,weapon:savedNumber(stored?.weapon,fallback.weapon),autoAttack:savedNumber(stored?.autoAttack,savedNumber(legacy.autoAttack,fallback.autoAttack)),aaInterval:savedNumber(stored?.aaInterval,savedNumber(legacy.aaInterval,fallback.aaInterval)),main:savedNumber(stored?.main,fallback.main),crit:savedNumber(stored?.crit,fallback.crit),dh:savedNumber(stored?.dh,fallback.dh),det:savedNumber(stored?.det,fallback.det),speed:savedNumber(stored?.speed,fallback.speed),tenacity:savedNumber(stored?.tenacity,fallback.tenacity),gcd:savedNumber(stored?.gcd,fallback.gcd)});
const expectedCritDh=(base:number,s:Stats,mod:{sub:number;div:number})=>{const critDelta=Math.floor(200*(s.crit-mod.sub)/mod.div),critRate=Math.max(0,Math.min(1,(critDelta+50)/1000)),critPower=1400+critDelta,dhRate=Math.max(0,Math.min(1,Math.floor(550*(s.dh-mod.sub)/mod.div)/1000)),normal=base,crit=Math.floor(base*critPower/1000),dh=Math.floor(base*125/100),cdh=Math.floor(crit*125/100);return normal*(1-critRate)*(1-dhRate)+crit*critRate*(1-dhRate)+dh*(1-critRate)*dhRate+cdh*critRate*dhRate};
const damageFactors=(s:Stats,job:string)=>{const mod=LEVEL_MODS[s.level]||LEVEL_MODS[100],tank=TANKS.has(job),attackCoeff=tank?mod.tankAttack:mod.attack,fAtk=Math.floor(attackCoeff*(s.main-mod.main)/mod.main)+100,fDet=Math.floor(140*(s.det-mod.main)/mod.div+1000),fTnc=tank?Math.floor(112*(s.tenacity-mod.sub)/mod.div+1000):1000,fWd=Math.floor(mod.main*JOB_MOD[job]/1000)+s.weapon,fSpd=Math.floor(130*(s.speed-mod.sub)/mod.div+1000);return{mod,fAtk,fDet,fTnc,fWd,fSpd,trait:TRAIT[job]||100}};
const directDamage=(potency:number,s:Stats,job:string)=>{const f=damageFactors(s,job);let value=Math.floor(potency*f.fAtk*f.fDet/100/1000);value=Math.floor(value*f.fTnc/1000);value=Math.floor(value*f.fWd/100);value=Math.floor(value*f.trait/100);return expectedCritDh(value,s,f.mod)};
const autoDamage=(s:Stats,job:string)=>{const f=damageFactors(s,job),fAuto=Math.floor(f.fWd*(s.aaInterval/3));let value=Math.floor(s.autoAttack*f.fAtk*f.fDet/100/1000);value=Math.floor(value*f.fTnc/1000);value=Math.floor(value*f.fSpd/1000);value=Math.floor(value*fAuto/100);value=Math.floor(value*f.trait/100);return expectedCritDh(value,s,f.mod)};

function calculate(rows:TimelineRow[],stats:Stats,job:string):ComputedRow[]{
  let nextGcd=0,nextOgcd=0,actionPotency=0,actionDamage=0;
  return rows.map(row=>{
    const prepare=row.actionId===null?row.time:row.time+Math.max(0,row.cast||0),damageEvent=prepare;
    if(row.modifier==="delay"||row.modifier==="downtime"){nextGcd=Math.max(nextGcd,row.time)+Math.max(0,row.modifierValue);nextOgcd=Math.max(nextOgcd,row.time)+Math.max(0,row.modifierValue)}
    else{if(row.lane==="gcd")nextGcd=Math.max(nextGcd,row.time)+(row.recast||stats.gcd);nextOgcd=Math.max(nextOgcd,row.time)+.7;actionPotency+=Math.max(0,row.potency);actionDamage+=directDamage(Math.max(0,row.potency),stats,job)}
    const aaCount=damageEvent>=0&&stats.aaInterval>0?Math.floor(damageEvent/stats.aaInterval)+1:0,sumPotency=actionPotency+aaCount*Math.max(0,stats.autoAttack),totalDamage=actionDamage+aaCount*autoDamage(stats,job);
    return {...row,prepare,damageEvent,nextGcd,nextOgcd,dps:damageEvent>0?totalDamage/damageEvent:0,sumPotency,aaCount,totalDamage};
  });
}

export default function Home(){
  const [job,setJob]=useState("PLD"),[sheets,setSheets]=useState<Sheet[]>([]),[active,setActive]=useState("");
  const [stats,setStats]=useState(STATS),[catalogs,setCatalogs]=useState<Record<string,CatalogAction[]>>({}),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState("");
  const [panel,setPanel]=useState<Panel>("timeline"),[filter,setFilter]=useState<ActionFilter>("damage"),[query,setQuery]=useState("");
  const [modifier,setModifier]=useState<Modifier>("none"),[modifierValue,setModifierValue]=useState(""),[bossOn,setBossOn]=useState(true),[saved,setSaved]=useState(false),[favoriteRevision,setFavoriteRevision]=useState(0),[draggingFavorite,setDraggingFavorite]=useState("");
  const hydrated=useRef(false),importInput=useRef<HTMLInputElement>(null);

  useEffect(()=>{const raw=localStorage.getItem("xiv-rotation-lab-v4")||localStorage.getItem("xiv-rotation-lab-v3")||localStorage.getItem("xiv-rotation-lab-v2");if(raw)try{const v=JSON.parse(raw),savedJob=JOBS.includes(v.job)?v.job:"PLD";setSheets((v.sheets||[]).map((s:Sheet)=>({...s,rows:(s.rows||[]).map(r=>({...r,cast:r.cast||0,recast:r.recast||0}))})));setActive(v.active||"");setJob(savedJob);setStats(normalizeStats(v.stats,STATS,{autoAttack:v.configs?.[savedJob]?.aaPotency,aaInterval:v.configs?.[savedJob]?.aaInterval??AA_INTERVALS[savedJob]}))}catch{}hydrated.current=true},[]);
  useEffect(()=>{if(!hydrated.current)return;if(!sheets.some(s=>s.job===job)){const s=newSheet(job);setSheets(v=>[...v,s]);setActive(s.id)}else if(!sheets.some(s=>s.id===active&&s.job===job)){setActive(sheets.find(s=>s.job===job)!.id)}},[job,sheets,active]);
  useEffect(()=>{if(!hydrated.current)return;const t=setTimeout(()=>{localStorage.setItem("xiv-rotation-lab-v4",JSON.stringify({sheets,active,job,stats}));setSaved(true);setTimeout(()=>setSaved(false),700)},250);return()=>clearTimeout(t)},[sheets,active,job,stats]);
  useEffect(()=>{if(Object.prototype.hasOwnProperty.call(catalogs,job))return;setLoading(true);setLoadError("");fetch(`/api/actions?job=${job}&level=100`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"アクションを取得できませんでした");return data}).then(data=>setCatalogs(v=>({...v,[job]:data.actions||[]}))).catch(error=>setLoadError(error instanceof Error?error.message:"アクションを取得できませんでした")).finally(()=>setLoading(false))},[job,catalogs]);

  const jobSheets=sheets.filter(s=>s.job===job),sheet=jobSheets.find(s=>s.id===active)||jobSheets[0],catalog=catalogs[job]||[];
  const rows=sheet?.rows||[],runtimeRows=rows.map(row=>{const source=row.actionId===null?undefined:catalog.find(action=>action.id===row.actionId);return source?{...row,potency:source.potency,cast:source.cast,recast:source.recast}:row}),computed=calculate(runtimeRows,stats,job),last=computed.at(-1),duration=Math.max(0,last?.damageEvent||0),total=last?.sumPotency||0,expected=last?.dps||0;
  const favoriteKey=`xiv-rotation-favorites:${job}`;
  const favoriteOrder=useMemo(()=>{if(typeof window==="undefined")return [] as string[];try{return JSON.parse(localStorage.getItem(favoriteKey)||"[]") as string[]}catch{return []}},[favoriteKey,favoriteRevision]),favorites=useMemo(()=>new Set(favoriteOrder),[favoriteOrder]);
  const shown=useMemo(()=>catalog.filter(a=>(a.level??1)<=stats.level&&a.name.includes(query)&&(filter==="damage"?a.hasDamage:filter==="support"?!a.hasDamage:filter==="gcd"?a.lane==="gcd":filter==="ability"?a.lane==="ability"||a.lane==="limitbreak":favorites.has(String(a.id)))).sort((a,b)=>filter==="custom"?favoriteOrder.indexOf(String(a.id))-favoriteOrder.indexOf(String(b.id)):(a.level??999)-(b.level??999)||a.id-b.id),[catalog,filter,query,stats.level,favorites,favoriteOrder]);
  const setRows=(next:TimelineRow[])=>setSheets(v=>v.map(s=>s.id===sheet?.id?{...s,rows:next}:s));
  const pick=(a:CatalogAction)=>{const lane:Lane=a.lane==="gcd"?"gcd":"ability",ready=lane==="gcd"?(last?.nextGcd||0):(last?.nextOgcd||0),base=Math.max(last?.time||0,ready),amount=Math.max(0,Number(modifierValue)||0),time=modifier==="pre"?base-amount:base;setRows([...rows,{id:crypto.randomUUID(),time,actionId:a.id,name:a.name,lane,potency:a.potency||0,cast:a.cast||0,recast:a.recast||0,boss:"",iconPath:a.iconPath,modifier,modifierValue:amount}]);setModifier("none");setModifierValue("")};
  const addPseudo=(kind:"delay"|"downtime")=>{const time=Math.max(last?.nextGcd||0,last?.nextOgcd||0,last?.time||0);setRows([...rows,{id:crypto.randomUUID(),time,actionId:null,name:kind==="delay"?"ディレイ":"ダウンタイム",lane:"ability",potency:0,cast:0,recast:0,boss:"",iconPath:"",modifier:kind,modifierValue:Math.max(.1,Number(modifierValue)||1)}]);setModifierValue("")};
  const addSheet=()=>{const s=newSheet(job,jobSheets.length+1);setSheets(v=>[...v,s]);setActive(s.id)};
  const deleteSheet=(target:Sheet)=>{if(!window.confirm(`「${target.name}」を削除しますか？\nこの操作は元に戻せません。`))return;const remaining=jobSheets.filter(s=>s.id!==target.id);setSheets(v=>v.filter(s=>s.id!==target.id));if(active===target.id)setActive(remaining[0]?.id||"")};
  const exportSheet=()=>{if(!sheet)return;const payload={format:"xiv-rotation-lab-sheet",version:1,exportedAt:new Date().toISOString(),stats,sheet:{name:sheet.name,job:sheet.job,rows:sheet.rows}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${sheet.job}-${sheet.name.replace(/[\\/:*?\"<>|]/g,"-")}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
  const importSheet=async(file?:File)=>{if(!file)return;try{const parsed=JSON.parse(await file.text()),source=parsed?.format==="xiv-rotation-lab-sheet"?parsed.sheet:parsed;if(!source||!JOBS.includes(source.job)||!Array.isArray(source.rows))throw new Error();const modifiers:Modifier[]=["none","delay","downtime","pre"],rows:TimelineRow[]=source.rows.map((r:Partial<TimelineRow>)=>({id:crypto.randomUUID(),time:Number(r.time)||0,actionId:r.actionId===null?null:Number.isFinite(Number(r.actionId))?Number(r.actionId):null,name:String(r.name||""),lane:r.lane==="gcd"?"gcd":"ability",potency:Number(r.potency)||0,cast:Number(r.cast)||0,recast:Number(r.recast)||0,boss:String(r.boss||""),iconPath:String(r.iconPath||""),modifier:modifiers.includes(r.modifier as Modifier)?r.modifier as Modifier:"none",modifierValue:Number(r.modifierValue)||0}));const imported:Sheet={id:crypto.randomUUID(),name:String(source.name||"インポートしたシート"),job:source.job,rows};setSheets(v=>[...v,imported]);if(parsed?.stats)setStats(normalizeStats(parsed.stats,stats));setJob(imported.job);setActive(imported.id)}catch{window.alert("シートを読み込めませんでした。XIV Rotation LabのJSONファイルを選択してください。")}finally{if(importInput.current)importInput.current.value=""}};
  const updateRow=(id:string,patch:Partial<TimelineRow>)=>setRows(rows.map(r=>r.id===id?{...r,...patch}:r));
  const saveFavoriteOrder=(order:string[])=>{localStorage.setItem(favoriteKey,JSON.stringify(order));setFavoriteRevision(v=>v+1)};
  const toggleFavorite=(id:number)=>{const key=String(id);saveFavoriteOrder(favorites.has(key)?favoriteOrder.filter(x=>x!==key):[...favoriteOrder,key])};
  const reorderFavorite=(target:string)=>{if(!draggingFavorite||draggingFavorite===target)return;const next=favoriteOrder.filter(x=>x!==draggingFavorite),index=next.indexOf(target);next.splice(index<0?next.length:index,0,draggingFavorite);saveFavoriteOrder(next);setDraggingFavorite("")};
  const retryActions=()=>setCatalogs(v=>{const next={...v};delete next[job];return next});

  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">X</span><div><strong>XIV ROTATION LAB</strong><small>SYSTEM PROTOTYPE</small></div></div><nav><Nav value="timeline" panel={panel} setPanel={setPanel}>TIMELINE</Nav><Nav value="stats" panel={panel} setPanel={setPanel}>STATS</Nav></nav></header>
    <section className="sheet-head"><div><p className="eyebrow">JOB WORKSPACE</p><div className="job-title"><select value={job} onChange={e=>setJob(e.target.value)}>{JOBS.map(j=><option key={j} value={j}>{j} — {JOB_NAMES[j]}</option>)}</select><label className="level-select">LEVEL<select value={stats.level} onChange={e=>setStats({...stats,level:Number(e.target.value)})}>{[70,80,90,100].map(level=><option key={level} value={level}>Lv. {level}</option>)}</select></label><h1>{JOB_NAMES[job]} ローテーション</h1></div></div><div className="sheet-tools"><button onClick={()=>importInput.current?.click()}>インポート</button><button onClick={exportSheet} disabled={!sheet}>エクスポート</button><input ref={importInput} type="file" accept="application/json,.json" hidden onChange={e=>importSheet(e.target.files?.[0])}/><div className="tabs">{jobSheets.map(s=><span key={s.id} className={`sheet-tab ${s.id===sheet?.id?"active":""}`}><button onClick={()=>setActive(s.id)}>{s.name}</button><button className="tab-delete" aria-label={`${s.name}を削除`} onClick={()=>deleteSheet(s)}>×</button></span>)}<button className="plus" aria-label="シートを追加" onClick={addSheet}>＋</button></div></div></section>
    <section className="metrics"><article><span>EXPECTED DPS</span><strong>{Math.round(expected).toLocaleString()}</strong><small>Allagan Studies式 / AA込み</small></article><article><span>ACTION DATA</span><strong>{loading?"…":loadError?"ERROR":catalog.length}</strong><small>{job} / Lv.{stats.level} / XIVAPI v2</small></article><article><span>SUM POTENCY</span><strong>{total.toLocaleString()}</strong><small>{duration.toFixed(1)} sec / AA {last?.aaCount||0}回</small></article><article><span>LOCAL SAVE</span><strong>{saved?"SAVED":"READY"}</strong><small>job-scoped schema v4</small></article></section>
    {loadError&&<section className="api-error"><span>アクション取得に失敗しました：{loadError}</span><button onClick={retryActions}>再取得</button></section>}

    {panel==="timeline"&&<section className="timeline-workbench">
      <ActionDock shown={shown} loading={loading} loadError={loadError} filter={filter} setFilter={setFilter} query={query} setQuery={setQuery} favorites={favorites} toggleFavorite={toggleFavorite} pick={pick} modifier={modifier} setModifier={setModifier} modifierValue={modifierValue} setModifierValue={setModifierValue} nextGcd={last?.nextGcd||0} nextOgcd={last?.nextOgcd||0} draggingFavorite={draggingFavorite} setDraggingFavorite={setDraggingFavorite} reorderFavorite={reorderFavorite}/>
      <div className="timeline-main"><div className="system-toolbar"><div className="modifier-controls"><input aria-label="修飾子の秒数" type="number" step=".1" placeholder="0" value={modifierValue} onChange={e=>setModifierValue(e.target.value)}/><span>秒</span><button onClick={()=>addPseudo("delay")}>DELAY</button><button onClick={()=>addPseudo("downtime")}>DOWNTIME</button></div><div className="timeline-actions"><button onClick={()=>setRows(rows.slice(0,-1))} disabled={!rows.length}>1つ戻す</button><button onClick={()=>setRows([])} disabled={!rows.length}>すべて消す</button></div><label><input type="checkbox" checked={bossOn} onChange={e=>setBossOn(e.target.checked)}/> ボスタイムライン</label></div>
        <div className="timeline-table-wrap"><table className="timeline-table"><thead><tr><th># / TIME</th><th>GCD</th><th>oGCD</th><th>POTENCY</th><th>PREPARE</th><th>NEXT GCD</th><th>NEXT oGCD</th><th>DPS</th><th>SUM POTENCY</th><th>AA</th>{bossOn&&<th>BOSS</th>}</tr></thead><tbody>{computed.map((r,i)=><tr key={r.id}><td className="row-time"><b>{String(i+1).padStart(2,"0")}</b><span>{timeText(r.time)}</span>{r.modifier!=="none"&&<em>{r.modifier} {r.modifierValue}</em>}</td><td>{r.lane==="gcd"?<ActionCell row={r} onDelete={id=>setRows(rows.filter(x=>x.id!==id))}/>:null}</td><td>{r.lane==="ability"?<ActionCell row={r} onDelete={id=>setRows(rows.filter(x=>x.id!==id))}/>:null}</td><td className="potency-cell">{r.actionId===null?"—":r.potency||"—"}</td><td>{decimal(r.prepare)}</td><td>{decimal(r.nextGcd)}</td><td>{decimal(r.nextOgcd)}</td><td className="damage">{Math.round(r.dps).toLocaleString()}</td><td>{r.sumPotency.toLocaleString()}</td><td>{r.aaCount}</td>{bossOn&&<td className={`boss-cell ${r.boss?"has-value":""}`}><input aria-label="ボスアクション" value={r.boss} onChange={e=>updateRow(r.id,{boss:e.target.value})}/></td>}</tr>)}</tbody></table>{!computed.length&&<div className="empty-state"><b>{job} のタイムラインは空です</b><span>左のアクションリストから使用順に選択してください。</span></div>}</div>
        <p className="snapshot-note">Prepare はバフ参照時刻です。詠唱アクションは詠唱完了時、無詠唱アクションは実行時点でスナップショットします。</p></div>
    </section>}
    {panel==="stats"&&<section className="form-card"><div className="section-title"><div><p className="eyebrow">CHARACTER INPUT</p><h2>{job} ステータス</h2></div></div><div className="form-grid">{Object.entries(stats).filter(([k])=>k!=="level").map(([k,v])=><label key={k}>{STAT_LABELS[k as keyof Stats]}<input type="number" value={v} step={["gcd","aaInterval","autoAttack"].includes(k)?.01:1} onChange={e=>setStats({...stats,[k]:Number(e.target.value)})}/></label>)}</div></section>}
    <footer><span><b className="dot"/> ジョブ別にブラウザ保存</span><span>Action source: XIVAPI v2 / ja</span></footer>
  </main>
}

function Nav({value,panel,setPanel,children}:{value:Panel;panel:Panel;setPanel:(v:Panel)=>void;children:React.ReactNode}){return <button className={panel===value?"nav-active":""} onClick={()=>setPanel(value)}>{children}</button>}

function ActionDock({shown,loading,loadError,filter,setFilter,query,setQuery,favorites,toggleFavorite,pick,modifier,setModifier,modifierValue,setModifierValue,nextGcd,nextOgcd,draggingFavorite,setDraggingFavorite,reorderFavorite}:{shown:CatalogAction[];loading:boolean;loadError:string;filter:ActionFilter;setFilter:(v:ActionFilter)=>void;query:string;setQuery:(v:string)=>void;favorites:Set<string>;toggleFavorite:(id:number)=>void;pick:(a:CatalogAction)=>void;modifier:Modifier;setModifier:(v:Modifier)=>void;modifierValue:string;setModifierValue:(v:string)=>void;nextGcd:number;nextOgcd:number;draggingFavorite:string;setDraggingFavorite:(v:string)=>void;reorderFavorite:(v:string)=>void}){
  return <aside className="action-dock"><div className="dock-heading"><div><p className="eyebrow">ACTION PALETTE</p><h2>アクション</h2></div><div className="ready-times"><span>NEXT GCD <b>{decimal(nextGcd)}</b></span><span>NEXT oGCD <b>{decimal(nextOgcd)}</b></span></div></div><input className="action-search" placeholder="アクションを検索" value={query} onChange={e=>setQuery(e.target.value)}/><div className="filter-tabs">{([["damage","ダメージあり"],["support","ダメージなし"],["gcd","GCD"],["ability","アビリティ"],["custom","カスタム"]] as [ActionFilter,string][]).map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className="dock-modifier"><span>次のアクション</span><select value={modifier} onChange={e=>setModifier(e.target.value as Modifier)}><option value="none">修飾子なし</option><option value="pre">PRE</option></select>{modifier==="pre"&&<><input aria-label="PRE秒数" type="number" min="0" step=".1" placeholder="0" value={modifierValue} onChange={e=>setModifierValue(e.target.value)}/><span>秒前</span></>}</div><div className="studio-action-list">{shown.map(a=>{const key=String(a.id);return <article key={`${a.id}:${a.name}`} draggable={filter==="custom"} className={draggingFavorite===key?"dragging":""} onDragStart={()=>setDraggingFavorite(key)} onDragEnd={()=>setDraggingFavorite("")} onDragOver={e=>{if(filter==="custom")e.preventDefault()}} onDrop={()=>reorderFavorite(key)}>{filter==="custom"&&<span className="drag-handle" title="ドラッグして並べ替え">⠿</span>}<button className="action-choice" onClick={()=>pick(a)}><img src={iconUrl(a.iconPath)} alt=""/><span><b>{a.name}</b><small>{a.lane==="gcd"?"GCD":a.lane==="limitbreak"?"LIMIT BREAK":"アビリティ"}{a.isReplacement?" · 置き換え":""} · Lv.{a.level??"—"} · 威力 {a.potency||"—"}</small></span></button><button className={favorites.has(key)?"favorite active":"favorite"} aria-label="お気に入り切替" onClick={()=>toggleFavorite(a.id)}>{favorites.has(key)?"★":"☆"}</button></article>})}{!shown.length&&<p className="no-results">{loading?"XIVAPIから取得しています…":loadError?"取得に失敗しました":"条件に一致するアクションがありません"}</p>}</div></aside>
}

function ActionCell({row,onDelete}:{row:TimelineRow;onDelete:(id:string)=>void}){return <span className={`action-cell ${row.modifier==="delay"||row.modifier==="downtime"?"pseudo":""}`}>{row.iconPath?<img src={iconUrl(row.iconPath)} alt=""/>:<i>{row.modifier==="delay"?"⏱":"⇥"}</i>}<span><b>{row.name}</b>{row.cast>0&&<small>CAST {row.cast.toFixed(1)}s</small>}</span><button aria-label="削除" onClick={()=>onDelete(row.id)}>×</button></span>}
